server:
  port: 8801

spring:
  cloud:
    compatibility-verifier:
      enabled: false
    config:
      server:
        git:
          uri: https://github.com/roudane2021/config-server-repo-ecommerce.git
  application:
    name: config-server

management:
  endpoints:
    web:
      exposure:
        include: refresh